dates: ["Jan. 26", "Jan. 28", "Jan. 29", "Feb. 2", "Feb. 4", "Feb. 9", "Feb. 11", "Feb. 12", "Feb. 16",
        "Feb. 18", "Feb. 23", "Feb. 25", "Mar. 1", "Mar. 3", "Mar. 8", "Mar. 10", "Mar. 11",
        "Mar. 22", "Mar. 24", "Mar. 29", "Mar. 31", "Apr. 5", "Apr. 7", "Apr. 12",
        "Apr. 14", "Apr. 19", "Apr. 21", "Apr. 26"]


lectures:
  - topic: <a href="https://CS287.github.io/Lectures/slides/lecture1.pdf" >Natural Language Processing</a>
    subtopic: Introduction
    hw: <a href="https://CS287.github.io/HW1/HW1.pdf" >HW1</a> (<a href="https://github.com/CS287/HW1" >Repo</a>) (<a href="https://inclass.kaggle.com/c/cs287-hw1/leaderboard">Kaggle</a>)
    papers:
      - name: "Manning (2016)"
        cite: "manning2016computational"
  - topic: Text Classification
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture2-textclassification.pdf" >Background and Naive Bayes</a>

    papers:
      - cite: bishop2006pattern
        name: "Bishop (2006) &sect; 4.2, 4.3"
      - cite: murphy2012
        name: "Murphy (2012) &sect; 3.5 "
      - name: "Wang and Manning (2012)"
        cite: wang2012baselines
  - topic:
    subtopic: Section <a href="http://nbviewer.jupyter.org/urls/cs287.github.io/Lectures/notebooks/TorchTutorial.ipynb" >Torch Notes</a>
    notes: <a href="http://torch.ch">Torch</a>

  - topic: ""
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture3-lr.pdf" >Multiclass Logistic Regression</a>
    hw: ""
    papers:
      - cite: murphy2012
        name: "Murphy (2012) &sect; 8.1-8.3 "
      - cite: berger1996maximum
        name: "Berger et al (1996)"

  - topic:
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture4-opt.pdf" >Hinge and Optimization</a>
    hw:
    notes: YG &sect; 6-6.1, , <a href="https://github.com/torch/optim">optim</a>
    papers:
      - cite: bottou2012stochastic
        name: "Bottou (2012)"
  - topic: Neural Networks
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture5-nn.pdf" >Tagging  + Bilinear Models</a>
    hw: <a href="https://CS287.github.io/HW2/HW2.pdf" >HW2</a> (<a href="https://github.com/CS287/HW2" >Repo</a>) (<a href="https://inclass.kaggle.com/c/cs287-hw2/leaderboard">Kaggle</a>)
    notes: YG &sect; 3, &sect; 4.1-4.5,
    papers:
      - name: "Santorini (1990)"
        cite: "santorini1990part"
      - name: "Collobert et al (2011)"
        cite: "collobert2011natural"
  - topic:
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture6-nn2.pdf" >Neural Networks</a>
    hw:
    notes: YG &sect; 5
    papers:
  - topic:
    subtopic: Section <a href="http://nbviewer.jupyter.org/urls/cs287.github.io/Lectures/notebooks/NNTutorial.ipynb" >Torch nn Notes</a>
    notes: <a href="https://github.com/torch/nn">Torch nn</a>

  - topic:
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture7-wc.pdf"> Word Embeddings </a> (<a href="http://nbviewer.jupyter.org/urls/cs287.github.io/Lectures/notebooks/vectors.ipynb">notebook</a>)
    hw:
    notes: YG &sect; 5
    papers:
        - name: Mikolov et al. (2013)
          cite: "mikolovchen"
        - name: Mnih and Hinton (2008)
          cite: "mnihhinton"

  - topic: Language Modeling
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture8-lm.pdf">Background </a>
    hw: 
    papers:
        - name: "Chen and Goodman (1999)"
          cite: "ChenG99"
        - name: "Heafield (2011)"
          cite: "heafield2011kenlm"
  - topic:
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture9-nlm.pdf">Neural Language Models</a>
    hw:
    papers:
        - name: "Bengio et al (2003)"
          cite: "DBLP:journals/jmlr/BengioDVJ03"
        - name: "Mnih and Teh (2012)"
          cite: "MnihT12"

    hw: <a href="https://CS287.github.io/HW3/HW3.pdf" >HW3</a> (<a href="https://github.com/CS287/HW3" >Repo</a>) (<a href="https://inclass.kaggle.com/c/cs287-hw3/leaderboard">Kaggle</a>)
  - topic:
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture10-conv.pdf">Convolutions</a>
    hw:
    notes: YG &sect; 9
    papers:
        - name: "Kalchbrenner et al (2014)"
          cite: "DBLP:conf/acl/KalchbrennerGB14"
        - name: "Kim (2014)"
          cite: "DBLP:conf/emnlp/Kim14"
        - name: "Zeiler and Fergus (2014)"
          cite: "DBLP:conf/eccv/ZeilerF14"
  - topic: Midterm
    subtopic:
    hw:
    papers:
  - topic: Recurrent Neural Networks
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture11-rnn.pdf">Fundamentals</a>
    hw: <a href="https://CS287.github.io/Projects/projects.pdf">Projects</a> (<a href="https://github.com/cs287/projects/wiki">Wiki</a>)
    notes: YG &sect; 10
    papers:
        - name: "Elman (1990)"
          cite: "DBLP:journals/cogsci/Elman90"
        - name: "Mikolov (2012)"
          cite: "tomavs2012statistical"
        - name: "Graves et al (2005)"
          cite: "DBLP:conf/icann/GravesFS05"
  - topic:
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture12-lstm.pdf">LSTMs and Language Modeling</a>
    hw: 
    notes: YG &sect; 11
    papers:
        - name: "Hochreiter and Schmidhuber (1997)"
          cite: "DBLP:journals/neco/HochreiterS97"
        - name: "Jozefowicz et al. (2015)"
          cite: "DBLP:conf/icml/JozefowiczZS15"
        - name: "Chung et al 2014"
          cite: "DBLP:journals/corr/ChungGCB14"
        - name: "Karpathy et al (2015)"
          cite: "DBLP:journals/corr/KarpathyJL15"
        - name: "Srivastava et al (2015)"
          cite: "DBLP:journals/corr/SrivastavaGS15"
  - topic: NLP Applications
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture13-applications.pdf">Overview</a>
    hw:<a href="https://CS287.github.io/HW4/HW4.pdf">HW 4</a> (<a href="https://github.com/CS287/HW4" >Repo</a>) (<a href="https://inclass.kaggle.com/c/cs287-hw4/leaderboard">Kaggle</a>)
    papers:
  - topic: Section
    subtopic: RNNs
    hw:
    papers:
  - topic: Application
    subtopic: Approximate Search
    hw:
    papers:

  - date: Mar. 29
    topic: Structured Prediction
    subtopic: Hidden Markov Models
    hw: HW 5
    papers:
  - date: Mar. 31
    topic:
    subtopic: Filtering, Smoothing, Viterbi
    hw:
    papers:
  - topic: Application
    subtopic: "Coreference"
    hw:
    papers:

  - topic: Conditional Random Fields
    subtopic: Training
    hw:
    papers:
  - topic:
    subtopic: Inference
    hw:
    papers:
  - topic: Application
    subtopic: Dependency Parsing
    hw:
    papers:
  - topic: Topics
    subtopic:
    hw:
    papers:
  - date: Apr. 19
    topic: Topics
    subtopic:
    hw:
    papers:
  - date: Apr. 21
    topic: Guest Lecture
    subtopic:
    hw:
    papers:
  - date: Apr. 26
    topic: Final Project Presentations
    subtopic:
    hw:
    papers:
