dates: ["Jan. 26", "Jan. 28", "Jan. 29", "Feb. 2", "Feb. 4", "Feb. 9", "Feb. 11", "Feb. 16",
        "Feb. 18", "Feb. 23", "Feb. 25", "Mar. 1", "Mar. 3", "Mar. 8", "Mar. 10",
        "Mar. 22", "Mar. 24", "Mar. 29", "Mar. 31", "Apr. 5", "Apr. 7", "Apr. 12",
        "Apr. 14", "Apr. 19", "Apr. 21", "Apr. 26"]


lectures:
  - topic: <a href="https://CS287.github.io/Lectures/slides/lecture1.pdf" >Natural Language Processing</a>
    subtopic: Introduction
    hw: <a href="https://CS287.github.io/HW1/HW1.pdf" >HW1</a> (<a href="https://github.com/CS287/HW1" >Repo</a>) (<a href="https://inclass.kaggle.com/c/cs287-hw1/leaderboard">Kaggle</a>)
    papers:
      - name: "Manning (2016)"
        cite: "manning2016computational"
  - topic: Text Classification
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture2-textclassification.pdf" >Background and Naive Bayes</a>

    papers:
      - cite: bishop2006pattern
        name: "Bishop (2006) &sect; 4.2, 4.3"
      - cite: murphy2012
        name: "Murphy (2012) &sect; 3.5 "
      - name: "Wang and Manning (2012)"
        cite: wang2012baselines
  - topic: 
    subtopic: Section <a href="http://nbviewer.jupyter.org/urls/cs287.github.io/Lectures/notebooks/TorchTutorial.ipynb" >Torch Notes</a>
    notes: <a href="http://torch.ch">Torch</a>
    
  - topic: ""
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture3-lr.pdf" >Multiclass Logistic Regression</a>
    hw: ""
    papers:
      - cite: murphy2012
        name: "Murphy (2012) &sect; 8.1-8.3 "
      - cite: berger1996maximum
        name: "Berger et al (1996)"
        
  - topic:
    subtopic: <a href="https://CS287.github.io/Lectures/slides/lecture4-opt.pdf" >Hinge and Optimization</a>
    hw:
    notes: YG &sect; 6-6.1
    papers:
      - cite: bottou2012stochastic
        name: "Bottou (2012)"
  - topic: Neural Networks
    subtopic: Background + Embeddings
    hw: <a href="https://CS287.github.io/HW2/HW2.pdf" >HW2</a> (<a href="https://github.com/CS287/HW2" >Repo</a>) (<a href="https://inclass.kaggle.com/c/cs287-hw2/leaderboard">Kaggle</a>)
    notes: YG &sect; 3, &sect; 4.1-4.5,
    papers:
  - topic:
    subtopic: Windowed Neural Networks
    hw:
    notes: YG &sect; 5
    papers:
      - name: "Collobert et al (2011)"
        cite: "collobert2011natural"
  - topic:
    subtopic: Convolutional Networks
    hw:
    notes: YG &sect; 9
    papers:
        - name: "Kalchbrenner et al (2014)"
          cite: "DBLP:conf/acl/KalchbrennerGB14"
        - name: "Kim (2014)"
          cite: "DBLP:conf/emnlp/Kim14"
  - topic: Language Modeling
    subtopic: Background + Smoothing
    hw: HW 3
  - topic:
    subtopic: Neural Language Models
    hw:
    papers:
        - name: "Bengio et al (2003)"
          cite: "DBLP:journals/jmlr/BengioDVJ03"
  - topic:
    subtopic: Word Embeddings and Visualization
    hw:
    notes: YG &sect; 5
    papers:
  - topic: Midterm
    subtopic:
    hw:
    papers:
  - topic: Recurrent Neural Networks
    subtopic: Fundamentals
    hw: HW 4
    notes: YG &sect; 10
    papers:
  - topic:
    subtopic: LSTMs and Language Modeling
    hw:
    notes: YG &sect; 11
    papers:
  - topic:
    subtopic: Approximate Search
    hw:
    papers:
  - topic: Application
    subtopic: "Machine Translation"
    hw:
    papers:

  - date: Mar. 29
    topic: Structured Prediction
    subtopic: Hidden Markov Models
    hw: HW 5
    papers:
  - date: Mar. 31
    topic:
    subtopic: Filtering, Smoothing, Viterbi
    hw:
    papers:
  - topic: Application
    subtopic: "Coreference"
    hw:
    papers:

  - topic: Conditional Random Fields
    subtopic: Training
    hw:
    papers:
  - topic:
    subtopic: Inference
    hw:
    papers:
  - topic: Application
    subtopic: Dependency Parsing
    hw:
    papers:
  - topic: Topics
    subtopic:
    hw:
    papers:
  - date: Apr. 19
    topic: Topics
    subtopic:
    hw:
    papers:
  - date: Apr. 21
    topic: Guest Lecture
    subtopic:
    hw:
    papers:
  - date: Apr. 26
    topic: Final Project Presentations
    subtopic:
    hw:
    papers:
